version: "3.8"

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    ports:
      - 8012:8000
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - 3012:5173
      - 3013:4173
    volumes:
      - ./frontend:/usr/src/app
    stdin_open: true
    tty: true

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8013:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www
    depends_on:
      - app

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: laravel

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped

volumes:
  postgres_data:
